[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  
[dev]
  command = "npm run dev"
  port = 3000
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 